import type { Project } from "@/lib/types"

export const projects: Project[] = [
  {
    id: "1",
    title: "Ampliación de Rancho Condominal",
    description: "Cunstrucción de un Rancho condominal con arquitectura moderna y sostenible.",
    image: "/images/ampliacion_rancho/1-6.webp?height=300&width=400&text=Residencial+Los+Pinos",
    gallery: [
      "/images/ampliacion_rancho/1-2.webp?height=400&width=600&text=de lado",
      "/images/ampliacion_rancho/1-3.webp?height=400&width=600&text=exterior",
      "/images/ampliacion_rancho/1-4.webp?height=400&width=600&text=atras",
      "/images/ampliacion_rancho/1-5.webp?height=400&width=600&text=2",
      "/images/ampliacion_rancho/1-6.webp?height=400&width=600&text=2",
      "/images/ampliacion_rancho/1-7.webp?height=400&width=600&text=2",
      "/images/ampliacion_rancho/1-8.webp?height=400&width=600&text=2",
      "/images/ampliacion_rancho/1-1.webp?height=400&width=600&text=2",
    ],
    category: "Residencial",
    location: "Zona Norte, Ciudad",
    area: "15,000 m²",
    year: "2025",
    client: "Inmobiliaria Norte S.A.",
    duration: "18 meses",
    features: [
      "50 unidades habitacionales",
      "Áreas verdes y parques",
      "Gimnasio y piscina",
      "Seguridad 24/7",
      "Estacionamiento subterráneo",
    ],
  },

  {
    id: "2",
    title: "Centro Comercial Plaza Central",
    description: "Moderno centro comercial con más de 100 locales comerciales, cines y área de comidas.",
    image: "/placeholder.svg?height=300&width=400&text=Centro+Comercial+Plaza",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Plaza+Central+Fachada",
      "/placeholder.svg?height=400&width=600&text=Plaza+Central+Interior",
      "/placeholder.svg?height=400&width=600&text=Plaza+Central+Cines",
      "/placeholder.svg?height=400&width=600&text=Plaza+Central+Food+Court",
    ],
    category: "Comercial",
    location: "Centro, Ciudad",
    area: "25,000 m²",
    year: "2022",
    client: "Grupo Comercial Central",
    duration: "24 meses",
    features: [
      "100+ locales comerciales",
      "Complejo de cines",
      "Área de comidas",
      "Estacionamiento para 500 vehículos",
      "Sistema de climatización central",
    ],
  },
  {
    id: "3",
    title: "Torre Corporativa Skyline",
    description: "Edificio de oficinas de 20 pisos con tecnología de punta y certificación LEED.",
    image: "/placeholder.svg?height=300&width=400&text=Torre+Corporativa",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Torre+Skyline+Exterior",
      "/placeholder.svg?height=400&width=600&text=Torre+Skyline+Lobby",
      "/placeholder.svg?height=400&width=600&text=Torre+Skyline+Oficinas",
      "/placeholder.svg?height=400&width=600&text=Torre+Skyline+Vista",
    ],
    category: "Corporativo",
    location: "Distrito Financiero",
    area: "30,000 m²",
    year: "2023",
    client: "Corporación Skyline",
    duration: "30 meses",
    features: [
      "20 pisos de oficinas",
      "Certificación LEED Gold",
      "Sistema de automatización",
      "Helipuerto",
      "Centro de conferencias",
    ],
  },
  {
    id: "4",
    title: "Conjunto Habitacional Verde",
    description: "Desarrollo sustentable con 80 casas ecológicas y sistemas de energía renovable.",
    image: "/placeholder.svg?height=300&width=400&text=Habitacional+Verde",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Verde+Casas+Solares",
      "/placeholder.svg?height=400&width=600&text=Verde+Jardines",
      "/placeholder.svg?height=400&width=600&text=Verde+Interior+Casa",
      "/placeholder.svg?height=400&width=600&text=Verde+Paneles+Solares",
    ],
    category: "Residencial",
    location: "Zona Sur, Ciudad",
    area: "12,000 m²",
    year: "2024",
    client: "EcoVivir Desarrollos",
    duration: "15 meses",
    features: [
      "80 casas ecológicas",
      "Paneles solares",
      "Sistema de recolección de agua",
      "Jardines comunitarios",
      "Estación de carga eléctrica",
    ],
  },
  {
    id: "5",
    title: "Hospital Regional Norte",
    description: "Moderno hospital con 200 camas, quirófanos de última generación y área de emergencias.",
    image: "/placeholder.svg?height=300&width=400&text=Hospital+Regional",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Hospital+Fachada",
      "/placeholder.svg?height=400&width=600&text=Hospital+Quirofanos",
      "/placeholder.svg?height=400&width=600&text=Hospital+Emergencias",
      "/placeholder.svg?height=400&width=600&text=Hospital+Habitaciones",
    ],
    category: "Salud",
    location: "Zona Norte, Ciudad",
    area: "18,000 m²",
    year: "2022",
    client: "Ministerio de Salud",
    duration: "36 meses",
    features: [
      "200 camas hospitalarias",
      "10 quirófanos modernos",
      "Área de emergencias 24/7",
      "Laboratorio especializado",
      "Helipuerto para emergencias",
    ],
  },
  {
    id: "6",
    title: "Complejo Educativo San José",
    description: "Campus educativo con aulas inteligentes, laboratorios y espacios deportivos.",
    image: "/placeholder.svg?height=400&width=600&text=Complejo+Educativo",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Educativo+Campus",
      "/placeholder.svg?height=400&width=600&text=Educativo+Aulas",
      "/placeholder.svg?height=400&width=600&text=Educativo+Laboratorios",
      "/placeholder.svg?height=400&width=600&text=Educativo+Deportes",
    ],
    category: "Educativo",
    location: "Zona Este, Ciudad",
    area: "8,000 m²",
    year: "2023",
    client: "Fundación Educativa San José",
    duration: "20 meses",
    features: [
      "30 aulas inteligentes",
      "Laboratorios de ciencias",
      "Biblioteca moderna",
      "Complejo deportivo",
      "Auditorio para 500 personas",
    ],
  },
]

