import type { Project } from "@/lib/types"

export const projects: Project[] = [
  {
    id: "1",
    title: "Ampliación de Rancho Condominal",
    description: "Construcción de un Rancho condominal con arquitectura moderna y sostenible.",
    image: "/images/ampliacion_rancho/1-6.webp?height=300&width=400&text=Residencial+Los+Pinos",
    gallery: [
      "/images/ampliacion_rancho/1-2.webp?height=400&width=600&text=de lado",
      "/images/ampliacion_rancho/1-3.webp?height=400&width=600&text=exterior",
      "/images/ampliacion_rancho/1-4.webp?height=400&width=600&text=atras",
      "/images/ampliacion_rancho/1-5.webp?height=400&width=600&text=2",
      "/images/ampliacion_rancho/1-6.webp?height=400&width=600&text=2",
      "/images/ampliacion_rancho/1-7.webp?height=400&width=600&text=2",
      "/images/ampliacion_rancho/1-8.webp?height=400&width=600&text=2",
      "/images/ampliacion_rancho/1-1.webp?height=400&width=600&text=2",
    ],
    category: "Residencial",
    location: "Guácima, Alajuela",
    area: "230 m²",
    year: "2025",
    client: "Condominio Valle Verde.",
    duration: "1 mes",
    features: [
      "50 unidades habitacionales",
      "Lamina de cuberta de techo esmaltada",
      "Madera Deck en piso y banca",
      "Estuctura Metálica",
      "Enchapes tipo porcelanato cerámica",
    ],
  },

  {
    id: "2",
    title: "Complejo Vacacional SB ",
    description: "Remodelación  completa del Ebais de Terraba.",
    image: "/images/cuqui/1.webp?height=300&width=400&text=Centro+Comercial+Plaza",
    gallery: [
      "/images/cuqui/1.webp?height=400&width=600&text=Complejo+SB",
       "/images/cuqui/2.webp?height=400&width=600&text=Complejo+SB",
      "/images/cuqui/3.webp?height=400&width=600&text=Complejo+SB",
       "/images/cuqui/5.webp?height=400&width=600&text=Complejo+SB",
    ],
    category: "Residencial",
    location: "Nandayure, Guanacaste",
    area: "450 m²",
    year: "2023",
    client: "Tecnotechos S.А",
    duration: "8 meses",
    features: [
      "6 módulos vacacionales, diseñados para alojamiento.",
      "Rancho con cocina compartida",
      "Piscina recreativa",
      "Rancho de descanso",
      "Piscina recreativa",
      "Sala de juegos",
     "bras exteriores en concreto,",
     "Tapia perimetral",
    ],
  },
  {
    id: "3",
    title: "Construcción del Ebais las Brisas",
    description: "Edificio de para la atención de pacientes del Seguro Social.",
    image: "/images/brisas/brisas1.webp?height=300&width=400&text=Torre+Corporativa",
    gallery: [
      "/images/brisas/2.webp?height=400&width=600&text=Ebais+brisas",
       "/images/brisas/3.webp?height=400&width=600&text=Ebais+brisas",
       "/images/brisas/4.webp?height=400&width=600&text=Ebais+brisas",
       "/images/brisas/5.webp?height=400&width=600&text=Ebais+brisas",
       "/images/brisas/6.webp?height=400&width=600&text=Ebais+brisas",
       "/images/brisas/7.webp?height=400&width=600&text=Ebais+brisas",
    ],
    category: "Salud",
    location: "Pérez Zeledón, San José",
    area: "230 m²",
    year: "2016",
    client: "Caja Costarrisence del Seguro Social",
    duration: "6 meses",
    features: [
      "Creación completa de edificio",
      "Certificación LEED Gold",
      "Renovación Electrica",
      "Cambio de fachada principal",
      
    ],
  },
  {
    id: "4",
    title: "Instalación de Cielo Suspendido Hospital México",
    description: "Suministro e instalación de Cielo Suspendido, Hospital México, CCSS. 2016LA-000004-2104.",
    image: "/images/cielomexico/cielo1.webp?height=300&width=400&text=Habitacional+Verde",
    gallery: [
      "/images/cielomexico/2.webp?height=400&width=600&text=cielo+suspendido",
      "/images/cielomexico/3.webp?height=400&width=600&text=cielo+suspendido",
      "/images/cielomexico/4.webp?height=400&width=600&text=cielo+suspendido",
      "/images/cielomexico/5.webp?height=400&width=600&text=cielo+suspendido",
      "/images/cielomexico/6.webp?height=400&width=600&text=cielo+suspendido",
      "/images/cielomexico/7.webp?height=400&width=600&text=cielo+suspendido",
      "/images/cielomexico/8.webp?height=400&width=600&text=cielo+suspendido",
      "/images/cielomexico/9.webp?height=400&width=600&text=cielo+suspendido",
    ],
    category: "Salud",
    location: "Uruca, San José",
    area: "9,000 m²",
    year: "2016",
    client: "Caja Costarrisence del Seguro Social",
    duration: "6 meses",
    features: [
      "Cambio de sielo suspendido",
      "Trabajo nocturno",
     
    ],
  },
  {
    id: "5",
    title: "Adición y mejoras a Edificios Hospital Monseñor Sanabria",
    description: "Construcción, adición o mejoras de Edificios Hospital Monseñor Sanabria, CCSS. 2015CD-0000077-2501.",
    image: "/images/ebaisdes/1.webp?height=300&width=400&text=Hospital+Monseñor+Sanabria",
    gallery: [
      "/images/ebaisdes/2.webp?height=300&width=400&text=Hospital+Monseñor+Sanabria",
      "/images/ebaisdes/3.webp?height=300&width=400&text=Hospital+Monseñor+Sanabria",
       "/images/ebaisdes/4.webp?height=300&width=400&text=Hospital+Monseñor+Sanabria",
       "/images/ebaisdes/5.webp?height=300&width=400&text=Hospital+Monseñor+Sanabria",
        "/images/ebaisdes/6.webp?height=300&width=400&text=Hospital+Monseñor+Sanabria",
         "/images/ebaisdes/7.webp?height=300&width=400&text=Hospital+Monseñor+Sanabria",
          "/images/ebaisdes/8.webp?height=300&width=400&text=Hospital+Monseñor+Sanabria",
           "/images/ebaisdes/9.webp?height=300&width=400&text=Hospital+Monseñor+Sanabria",
    ],
    category: "Salud",
    location: "Zona Norte, Ciudad",
    area: "162 m²",
    year: "2015",
    client: "Caja Costarrisence del Seguro Social",
    duration: "7 meses",
    features: [
      "Paso entre edificios",
      "Mejora en pintura",
      "Mejoras en techos y canoas",
      "Creacion de zonas verdes",
    ],
  },
  {
    id: "6",
    title: "Ampliación de Sala de Masajes UTN",
    description: "Ampliación de la Sala de Masajes, Universidad Técnica Nacional. 2014LA-00001-UTN01",
    image: "/images/UTN/4.webp?height=400&width=600&text=UTN+Educativo",
    gallery: [
      "/images/UTN/1.webp?height=400&width=600&text=UTN+Educativo",
      "/images/UTN/2.webp?height=400&width=600&text=UTN+Educativo",
      "/images/UTN/3.webp?height=400&width=600&text=UTN+Educativo",
      "/images/UTN/5.webp?height=400&width=600&text=UTN+Educativo"
    ],
    category: "Educativo",
    location: "UTN, Alajuela",
    area: "292 m²",
    year: "2014",
    client: "Universidad Técnica Nacional",
    duration: "6 meses",
    features: [
      "Renovación de baños",
      "Pintura de interiores",
      "Renovacion de Fachada Exterior",
    
    ],
  },
]

