import type { Project } from "@/lib/types"

export const projects: Project[] = [
  {
    id: "1",
    title: "Ampliación de Rancho Condominal",
    description: "Construcción de un Rancho condominal con arquitectura moderna y sostenible.",
    image: "/images/ampliacion_rancho/1-6.webp?height=300&width=400&text=Residencial+Los+Pinos",
    gallery: [
      "/images/ampliacion_rancho/1-2.webp?height=400&width=600&text=de lado",
      "/images/ampliacion_rancho/1-3.webp?height=400&width=600&text=exterior",
      "/images/ampliacion_rancho/1-4.webp?height=400&width=600&text=atras",
      "/images/ampliacion_rancho/1-5.webp?height=400&width=600&text=2",
      "/images/ampliacion_rancho/1-6.webp?height=400&width=600&text=2",
      "/images/ampliacion_rancho/1-7.webp?height=400&width=600&text=2",
      "/images/ampliacion_rancho/1-8.webp?height=400&width=600&text=2",
      "/images/ampliacion_rancho/1-1.webp?height=400&width=600&text=2",
    ],
    category: "Residencial",
    location: "Guácima, Alajuela",
    area: "230 m²",
    year: "2025",
    client: "Condominio Valle Verde.",
    duration: "1 mes",
    features: [
      "50 unidades habitacionales",
      "Lamina de cuberta de techo esmaltada",
      "Madera Deck en piso y banca",
      "Estuctura Metálica",
      "Enchapes tipo porcelanato cerámica",
    ],
  },

  {
    id: "2",
    title: "Remodelación del Ebais Terraba ",
    description: "Remodelación  completa del Ebais de Terraba.",
    image: "/images/terraba/1.jpg?height=300&width=400&text=Centro+Comercial+Plaza",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Plaza+Central+Fachada",
      "/placeholder.svg?height=400&width=600&text=Plaza+Central+Interior",
      "/placeholder.svg?height=400&width=600&text=Plaza+Central+Cines",
      "/placeholder.svg?height=400&width=600&text=Plaza+Central+Food+Court",
    ],
    category: "Salud",
    location: "Golfito, Puntarenas",
    area: "400 m²",
    year: "2016",
    client: "Caja Costarrisence del Seguro Social",
    duration: "4 meses",
    features: [
      "Remodelación completa",
      "Creación de cerca perimetral",
      "Creación de consultorios",
     
    ],
  },
  {
    id: "3",
    title: "Construcción del Ebais las Brisas",
    description: "Edificio de para la atención de pacientes del Seguro Social.",
    image: "/images/brisas/brisas1.webp?height=300&width=400&text=Torre+Corporativa",
    gallery: [
      "/images/brisas/2.webp?height=400&width=600&text=Ebais+brisas",
       "/images/brisas/3.webp?height=400&width=600&text=Ebais+brisas",
       "/images/brisas/4.webp?height=400&width=600&text=Ebais+brisas",
       "/images/brisas/5.webp?height=400&width=600&text=Ebais+brisas",
       "/images/brisas/6.webp?height=400&width=600&text=Ebais+brisas",
       "/images/brisas/7.webp?height=400&width=600&text=Ebais+brisas",
    ],
    category: "Salud",
    location: "Perez Zeledón, San José",
    area: "2000 m²",
    year: "2016",
    client: "Caja Costarrisence del Seguro Social",
    duration: "6 meses",
    features: [
      "Creación completa de edificio",
      "Certificación LEED Gold",
      "Renovación Electrica",
      "Cambio de fachada principal",
      
    ],
  },
  {
    id: "4",
    title: "Instalación de Cielo Suspendido Hospital México",
    description: "Suministro e instalación de Cielo Suspendido, Hospital México, CCSS. 2016LA-000004-2104.",
    image: "/images/cielomexico/cielo1.webp?height=300&width=400&text=Habitacional+Verde",
    gallery: [
      "/images/cielomexico/2.webp?height=400&width=600&text=cielo+suspendido",
      "/images/cielomexico/3.webp?height=400&width=600&text=cielo+suspendido",
      "/images/cielomexico/4.webp?height=400&width=600&text=cielo+suspendido",
      "/images/cielomexico/5.webp?height=400&width=600&text=cielo+suspendido",
      "/images/cielomexico/6.webp?height=400&width=600&text=cielo+suspendido",
      "/images/cielomexico/7.webp?height=400&width=600&text=cielo+suspendido",
      "/images/cielomexico/8.webp?height=400&width=600&text=cielo+suspendido",
      "/images/cielomexico/9.webp?height=400&width=600&text=cielo+suspendido",
    ],
    category: "Salud",
    location: "Uruca, San José",
    area: "9,000 m²",
    year: "2016",
    client: "Caja Costarrisence del Seguro Social",
    duration: "6 meses",
    features: [
      "Cambio de sielo suspendido",
      "Trabajo nocturno",
     
    ],
  },
  {
    id: "5",
    title: "Adición y mejoras a Edificios Hospital Monseñor Sanabria",
    description: "Construcción, adicción o mejoras de Edificios Hospital Monseñor Sanabria, CCSS. 2015CD-0000077-2501.",
    image: "/images/ebaisdes/1.jpg?height=300&width=400&text=Hospital+Regional",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Hospital+Fachada",
      "/placeholder.svg?height=400&width=600&text=Hospital+Quirofanos",
      "/placeholder.svg?height=400&width=600&text=Hospital+Emergencias",
      "/placeholder.svg?height=400&width=600&text=Hospital+Habitaciones",
    ],
    category: "Salud",
    location: "Zona Norte, Ciudad",
    area: "800 m²",
    year: "2022",
    client: "Caja Costarrisence del Seguro Social",
    duration: "36 meses",
    features: [
      "Paso entre edificios",
      "Mejora en pintura",
      "Mejoras en techos y canoas",
      "Creacion de zonas verdes",
    ],
  },
  {
    id: "6",
    title: "Ampliación de Sala de Masajes UTN",
    description: "Campus educativo con aulas inteligentes, laboratorios y espacios deportivos.",
    image: "/placeholder.svg?height=400&width=600&text=Complejo+Educativo",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Educativo+Campus",
      "/placeholder.svg?height=400&width=600&text=Educativo+Aulas",
      "/placeholder.svg?height=400&width=600&text=Educativo+Laboratorios",
      "/placeholder.svg?height=400&width=600&text=Educativo+Deportes",
    ],
    category: "Educativo",
    location: "Zona Este, Ciudad",
    area: "8,000 m²",
    year: "2023",
    client: "Fundación Educativa San José",
    duration: "20 meses",
    features: [
      "30 aulas inteligentes",
      "Laboratorios de ciencias",
      "Biblioteca moderna",
      "Complejo deportivo",
      "Auditorio para 500 personas",
    ],
  },
]

